server:
  port: 8085

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
          ## Discover Server Route
        - id: SERVICE-REGISTRY
          uri: http://localhost:8084
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
          ## Discover Server Static Resources Route
        - id: SERVICE-REGISTRY-STATIC
          uri: http://localhost:8084
          predicates:
            - Path=/eureka/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hotels/**,/api/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/ratings/**
#  config:
#    import: configserver:http://localhost:8086

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8084/eureka