apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  selector:
    matchLabels:
      app: api-gateway-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway-deployment
    spec:
      containers:
        - name: api-gateway-deployment
          image: devkrishnagupta/testing-hotel-management-api-gateway
          ports:
            - containerPort: 8085
          env:   # Setting Enviornmental Variables
            - name: spring.profiles.active   # Setting Database host address from configMap
              value: k8s
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: api-gateway
spec:
  selector:
    app: api-gateway-deployment
  ports:
    - protocol: "TCP"
      port: 8085 # The port that the service is running on in the cluster
      targetPort: 8085 # The port exposed by the service
  type: LoadBalancer # type of the service.

