apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registory-deployment
spec:
  selector:
    matchLabels:
      app: service-registory-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: service-registory-deployment
    spec:
      containers:
        - name: service-registory-deployment
          image: devkrishnagupta/testing-hotel-management-service-registry
          ports:
            - containerPort: 8084
          env:   # Setting Enviornmental Variables
            - name: spring.profiles.active   # Setting Database host address from configMap
              value: k8s
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: service-registry
spec:
  selector:
    app: service-registory-deployment
  ports:
    - protocol: "TCP"
      port: 8084 # The port that the service is running on in the cluster
      targetPort: 8084 # The port exposed by the service
  type: LoadBalancer # type of the service.

